# Generated by Django 4.2 on 2022-12-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('state', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('sceneNo', models.AutoField(primary_key=True, serialize=False)),
                ('sceneName', models.CharField(max_length=20)),
                ('oriImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SceneEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sceneNo', models.IntegerField()),
                ('EquipmentNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('phoneNumber', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sceneNo', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
