# Generated by Django 4.2 on 2022-12-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='oriImage',
            field=models.URLField(),
        ),
    ]
