# Generated by Django 4.2 on 2022-12-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_alter_scene_oriimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='no',
            new_name='sceneNo',
        ),
    ]
