# Generated by Django 4.2 on 2022-12-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_rename_no_equipment_sceneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sceneequipment',
            old_name='EquipmentNo',
            new_name='equipmentNo',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='sceneNo',
        ),
    ]
