# Generated by Django 4.2 on 2022-12-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_rename_equipmentno_sceneequipment_equipmentno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SceneEquipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='sceneNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
